### ISSUE TITLE
manage version info without requiring installation of script

### ISSUE THREAD

**Issue by vphill** [unt-libraries/warc-metadata-sidecar#12]
right now warc_metadata_sidecar.py is self contained and can be run as a script very easily without installation, _if_ you didn't have to have it installed to get the version info for the warc records.  

Can we look at a different way of documenting versions for this?  maybe `__version__` in the warc_metadata_sidecar.py file which is a pretty common way of doing that.  There might be some hoops that have to be jumped through in the setup.py file to have only a single source of version info if that is required. 

Something like this - https://gitlab.com/pymarc/pymarc/-/blob/main/docs/source/conf.py#L73-80 could be an approach in setup.py to get the version from the warc_metadata_sidecar.py file.

**Comment by ldko** [comment]
We use a `__version__` variable in [django-name](https://github.com/unt-libraries/django-name/blob/bfe1fa4e87f85764965117ced7ef5ef117413bdd/name/__init__.py) and [codalib](https://github.com/unt-libraries/codalib/blob/b287dd4328773418921ef1698dcafd1beecefa9d/codalib/__init__.py).
