### ISSUE TITLE
metadata-sidecar should work for ARC files also

### ISSUE THREAD

**Issue by gracieflores** [unt-libraries/warc-metadata-sidecar#2]
Warcio is able to read ARC files, but not write them. Will have to figure out something that can help with that.

**Comment by ldko** [comment]
We won't need to write actual ARC files for the sidecars, so we should be able to use warcio still to write the sidecar files theoretically. The issue I am thinking there may be is that ARC files don't have an equivalent of WARC fields, so there is no ID affiliated with what would be a "record" in an ARC file, so how do we want to tie the sidecar metadata records back to the ARC in a way that makes them usable? Do we need to convert the ARC files to WARC files?

**Comment by gracieflores** [comment]
With 1 line change the warc-metadata-sidecar works for ARC files too. At least with the 2 files I played with. Like you mentioned above, the ARC records do not contain a record ID. One gets generated for the sidecar, but there would be no way to link the sidecar records to the original ARC records they generated from. So, you asked a good question. `Do we need to convert the ARC files into WARC files?` @vphill

**Comment by vphill** [comment]
I think the metadata-sidecar should always generate WARC files as output. 
We shouldn't change the original files ie convert from arc-warc in this process (if that's what I am understanding). 
We can accept that there will be some functionality lost when using arc vs warc. 

Is that what you meant?

**Comment by gracieflores** [comment]
I think we were wondering if you need the WARC metadata sidecar file that gets generated to have a way to reference it's original individual records. The file itself will be referenced, but each record in the file would not have a reference to it's original record. WARC files that get processed through the warc-metadata-sidecar have this ID `WARC-Record-ID: <urn:uuid:956aff57-0466-4041-8c37-a0fd664871b4>` and that gets transferred to the sidecar that gets generated, but ARC files don't have any type of identifier. So you may have a sidecar with metadata, but no way to match each individual record on it.

**Comment by ldko** [comment]
@gracieflores it sounds like it is acceptable that we won't have an ID to explicitly tie the sidecar record to (such as WARC-Record-ID). So, I think it means we won't have `WARC-Concurrent-To` nor `WARC-Warcinfo-ID` in the sidecar records. @vphill do you think we should add a field in the sidecar records for something like `ARC-Filename-Concurrent-To`, so an individual sidecar record could theoretically be tied loosely/inprecisely back to the name of the ARC file it came from, or does this sound not particularly helpful?

**Comment by gracieflores** [comment]
Mark says we would likely use the uri and timestamp from the metadata sidecar, so I don't think we need to add anything extra. But I can remove the `WARC-Concurrent-To` and `WARC-Warcinfo-ID` from the metadata sidecar records when the file being processed is an ARC file.

**Comment by gracieflores** [comment]
When we process an ARC file, the extension will still change to warc.meta.gz?

ex:
file to process - LOC-ENDOFTERM-01-20090122204532-14087-crawling108.us.archive.org.arc.gz
sidecar generated - LOC-ENDOFTERM-01-20090122204532-14087-crawling108.us.archive.org.warc.meta.gz
