### ISSUE TITLE
Add soft 404 detection

### ISSUE THREAD

**Issue by gracieflores** [unt-libraries/warc-metadata-sidecar#4]
From GitLab repo urls2warc/-/issues/2#note_15998, Mark says:
"If we decide to try and do soft 404 detection something like this might be useful - https://github.com/dogancanbakir/soft-404
We would use it on pages that were recognized as html that have a status code of 200."

From slack, Mark says (April 13, 2022):
"If we can give the soft-404 a try https://github.com/dogancanbakir/soft-404 (just because we have the framework to try and make that happen) that could be cool.
If it seems like it will be quite a bit of effort to really make it work I do not have strong desires to go down that road right now.
But if it plugs in and seems to work ¯\_(ツ)_/¯ "

**Comment by gracieflores** [comment]
@vphill In adding soft404 detection, what output would you expect?

Here is a starting point for the sidecar payload:
```
Identified-Payload-Type: {'fido': 'application/xhtml+xml', 'python-magic': 'text/html'}
Preservation-Identifier: fmt/102
Charset-Detected: {'encoding': 'ascii', 'confidence': 1.0}
Languages-cld2: {'reliable': True, 'text-bytes': 1804, 'languages': [{'name': 'ENGLISH', 'code': 'en', 'text-covered': 99, 'score': 1189.0}]}
Soft-404-Detected: 0.6963556617840959

Also, do we only want to keep track of those with a probability of 50% and higher?

**Comment by vphill** [comment]
This looks reasonable to me. 

As for keeping track of things 50% and higher I think that can be done easily by a downstream client if they are interested in that information.
